language: python
python:
  - 3.6.2
install:
  - pip install -r requirements.txt
  - pip install coveralls  
script:
  - nosetests --with-coverage
  - coverage report
branches:
  only:
    -challenge2
after_success:
  - coveralls